create re-usable workflow for semgrep scan
janeapp/reusable-workflows pull request #3
Opened 2022-08-08 21:59 UTC by bodundeadebiyi

This PR creates a new re-usable github action workflow for semgrep scan. This workflow also makes use of semgrep's container image instead of the github action.

2022-08-10 15:05 UTC, bobop requested changes

2022-08-10 15:05 UTC, bobop commented on .github/workflows/semgrep-scan.yml
> +  semgrep_scan:
I think we ought to add a condition to skip this step if the PR creator is Dependabot:
```
# Skip any PR created by dependabot to avoid permission issues
if: (github.actor != 'dependabot[bot]')
```

2022-08-10 15:06 UTC, bobop commented
This reusable workflow has been proven to work from another repo during development:
<img width="952" alt="Screen Shot 2022-08-09 at 5 52 48 PM" src="https://user-images.githubusercontent.com/303586/183939306-2df917bd-b483-40d2-8171-df3b69bb1cf7.png">

2022-08-15 18:26 UTC, bodundeadebiyi commented on .github/workflows/semgrep-scan.yml
> +  semgrep_scan:
Don't you think it's better to have this bit of logic in the github actions that call this workflow? I don't know if there'll ever be a scenario where we'd want to run this semgrep scan for dependabot PR's but if that ever arises then we wouldn't have to create a separate reusable workflow for that situation.

2022-08-15 19:59 UTC, bobop approved these changes

2022-08-15 23:40 UTC, merged