Ci/hunter release checkout all
janeapp/reusable-workflows pull request #42
Opened 2023-09-14 19:29 UTC by hyperwidget

2023-09-14 19:31 UTC, hyperwidget commented on .github/workflows/release-frontend-app.yml
> -          type: string
All auto formatting above

2023-09-14 19:32 UTC, hyperwidget commented on .github/workflows/release-frontend-app.yml
> +        run: git fetch --tags
above changes from Val's previous work

2023-09-14 19:32 UTC, hyperwidget commented on .github/workflows/deploy-frontend-app.yml
> +      is-canary:
Added is canary flag, defaulting to false

2023-09-14 19:32 UTC, hyperwidget commented on .github/workflows/deploy-frontend-app.yml
> +          unzip build${{inputs.version_number}}.zip
custom logic for fetching and unpacking canary

2023-09-14 20:02 UTC, carvallegro requested changes

2023-09-14 20:02 UTC, carvallegro commented on .github/workflows/deploy-frontend-app.yml
> +          unzip build${{inputs.version_number}}.zip
Very small nitpick but how do you feel about adding a comment to explicitely indicate and document the branching flow between canary and non canary?

2023-09-18 16:04 UTC, carvallegro approved these changes

2023-09-18 20:11 UTC, merged