push semgrep scan to defectdojo
janeapp/reusable-workflows pull request #7
Opened 2022-09-21 02:53 UTC by bodundeadebiyi

In this PR we are modifying our reusable semgrep-scan github action to not only run semgrep scans but to also push the report to defectdojo and not just the semgrep dashboard. Reports pushed to the semgrep dashboard gets deleted/archived after three months and that is why we have decided to push this report to defectdojo where it doesn't get archived.

2022-09-22 16:06 UTC, bobop requested changes
Thanks @bodundeadebiyi for this work 👍 

I have a few comments and thoughts...

2022-09-22 16:06 UTC, bobop commented on .github/workflows/semgrep-scan.yml
> +      - name: report to defectdojo
At the moment we will only want to POST the Semgrep Scan on Pull Requests, not merges to the default branch, so we ought to add an `if` condition here:

```
- name: Push Semgrep output to DefectDojo
  if: github.event_name == 'pull_request' # Run on pull_request trigger
  run: |
  ...
```

The reason we are not POSTing reports from merges to the default branch yet is because we haven't figured out where or how DefectDojo should store these scan reports yet.

2022-09-22 16:06 UTC, bobop commented on .github/workflows/semgrep-scan.yml
> +      - run: semgrep ci --json --output report.json
Do these commands stop findings going to Semgrep itself? I'd still want findings to go there as well as to DefectDojo

2022-09-22 16:06 UTC, bobop commented on .github/workflows/semgrep-scan.yml
> +      - name: install cURL
I'm not sure this step is necessary - the brakeman reusable workflow uses cURL without installing it beforehand. I think curl is available to any Github Action

2022-09-23 00:07 UTC, bodundeadebiyi commented on .github/workflows/semgrep-scan.yml
> +      - name: install cURL
It returns a `cURL not found` error because the semgrep github action runs on the `returntocorp/semgrep` image which is based on linux alpine which doesn't have cURL in it by default.

2022-09-23 00:07 UTC, bodundeadebiyi commented on .github/workflows/semgrep-scan.yml
> +      - run: semgrep ci --json --output report.json
No it doesn't.

2022-09-23 00:17 UTC, bodundeadebiyi commented on .github/workflows/semgrep-scan.yml
> +          -F "engagement_name=Semgrep Scan" \
done

2022-09-23 00:17 UTC, bodundeadebiyi commented on .github/workflows/semgrep-scan.yml
> +      - name: report to defectdojo
done

2022-09-23 00:17 UTC, bodundeadebiyi commented on .github/workflows/semgrep-scan.yml
> +          -F "test_title=Semgrep Scan" \
done

2022-09-26 18:35 UTC, bobop commented on .github/workflows/semgrep-scan.yml
> +      - name: report to defectdojo
The `if` condition needs to be on this `- name: report to defectdojo` step because we still want Semgrep to run when the trigger is a push to the default branch (not a PR push), but we don't wan't the POST to DefectDojo when the trigger is a push to the default branch.

2022-09-26 21:20 UTC, bodundeadebiyi commented on .github/workflows/semgrep-scan.yml
> +      - name: report to defectdojo
this has been addressed

2022-09-26 21:26 UTC, bobop approved these changes

2022-09-26 21:26 UTC, merged